extends:
  - '@commitlint/config-conventional'
rules:
  type-enum:
    - 2
    - always
    - - build
      - ci
      - perf
      - feat
      - fix
      - refactor
      - docs
      - chore
      - style
      - revert
      - test
  type-empty:
    - 2
    - never
  header-max-length:
    - 0
    - always
    - 255
