env:
  browser: true
  es2021: true
  vue/setup-compiler-macros: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/base
  - plugin:vue/vue3-recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
