env:
  browser: true
  es2021: true
  vue/setup-compiler-macros: true
extends:
  - eslint:recommended
  - 'plugin:vue/base'
  - 'plugin:vue/vue3-recommended'
  - plugin:@typescript-eslint/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  parser:
    - vue
    - '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - prettier
rules: { prettier/prettier: 2 }
